### ISSUE TITLE
Unable to sign request without credentials set

### ISSUE THREAD

**Issue by Plaristote** [customink/activerecord-aurora-serverless-adapter#34]
Greetings ! I've been unable to open a connection to an RDS Aurora database, and I'm no expert on AWS API, so I might've been missing something obvious...

But it seems to me like `Aws::RDSDataService::Client` requires a `credentials` parameter. The readme doesn't specify how these credentials are supposed to be given. I'm not sure it can be done through the config file.

I've been able to solve the issue by patching this gem, by editing `lib/active_record/connection_adapters/aurora_serverless/client.rb` and adding the following line just before the instantiation of the `Aws::RDSDataService::Client`:
```
  options[:credentials] = Aws::Credentials.new options[:access_key]["id"], options[:access_key]["secret"]
```

I am then able to add my credentials to my config file as such:
```
aurora: &aurora
  adapter: aurora_serverless
  region: 'eu-west-2'
  access_key:
    id: "access_key_id"
    secret: "secret_access_key"
  resource_arn: "---"
  secret_arn: "---"
```

And it seems to work (I don't have access to any aws resource yet, but it _seems_ to work).
I'm wondering:

- If there's another way to do that, shouldn't we talk about it in the README ?
- Or should I make a PR so we can work on implementing that in the gem ? And if so, any hints on how you'd want this to be done ?
